version: "3.9"

services:
  kindle-bot:
    build: .
    container_name: kindle-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/data   # база будет доступна на хосте в ./data/users.db
      - ./tmp:/tmp     # (опционально) временные файлы