name: Deploy to Server

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy over SSH
      run: |
        ssh -tt -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          echo "--- Connected to server and starting deployment ---"
          cd /root/tg-to-kindle
          git pull
          docker-compose down
          docker-compose up -d --build
        EOF

    - name: Deploy over SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /root/tg-to-kindle
          git pull
          docker-compose down
          docker-compose up -d --build
        EOF